# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ stdenv, cabal, errors, regexTdfa, transformers, xml }:

cabal.mkDerivation (self: {
  pname = "autonix-deps";
  version = "0.1.0.0";
  src = builtins.filterSource (path: type: baseNameOf path != "dist") ./.;
  buildDepends = [ errors regexTdfa transformers xml ];
  meta = {
    description = "Library for Nix expression dependency generation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
