# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, conduit, errors, filepath, lens, libarchiveConduit, mtl
, optparseApplicative, regexTdfa, resourcet, transformers, xml
}:

cabal.mkDerivation (self: {
  pname = "autonix-deps";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    conduit errors filepath lens libarchiveConduit mtl
    optparseApplicative regexTdfa resourcet transformers xml
  ];
  meta = {
    description = "Library for Nix expression dependency generation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
